### ISSUE TITLE
Need some free BTC Testnet RPC server information

### ISSUE THREAD

**Issue by zydjohnHotmail** [mahsumurebe/nestjs-bitcoin-rpc-client#1]
Hello:
I want to use the repo to test some BTC RPC calls, but I want to
find some public BTC testnet RPC server, I need some IP address and port number, I don't want to setup a localhost RPC server.
Please advise where I can find such BTC RPC servers on testnet.
Thanks,

**Comment by mahsumurebe** [comment]
Hi.

For public rpc servers, you can visit [getblock.io](https://getblock.io/nodes/btc/). But if you need an rpc server to test this repo you can try bitcoin regtest.

You can check this [gist](https://gist.github.com/System-Glitch/cb4e87bf1ae3fec9925725bb3ebe223a) to learn how to use the regtest mode.
